name: booking-order-app
services:
  user-service:
    container_name: user-service
    # image: bintangnugraha/user-service:17
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
